version: "3"

services:
  composer:
    image: behat_php
    cap_drop: [all]
    working_dir: /var/www/html
    entrypoint: composer
    volumes:
      - .:/var/www/html:cached
  behat:
    image: behat_php
    cap_drop: [all]
    working_dir: /var/www/html
    entrypoint: vendor/bin/behat
    volumes:
      - .:/var/www/html:cached
